version: '3.8'

services:
  nginx-rtmp:
    build: .
    container_name: nginx-rtmp-proxy
    ports:
      - "1935:1935"  # RTMP port
      - "80:80"       # HTTP port
      - "443:443"     # HTTPS port
    environment:
      - ORYX_SERVER_1=${ORYX_SERVER_1:-area.quantumatic.live/live}
      - ORYX_SERVER_2=${ORYX_SERVER_2:-your-target-server-2.com:1935}
      - WHEP_SERVER_1=${WHEP_SERVER_1:-area.quantumatic.live:443}
      - WHEP_HOST_1=${WHEP_HOST_1:-area.quantumatic.live}
      - WHEP_SERVER_2=${WHEP_SERVER_2:-area-2.quantumatic.live:443}
      - WHEP_HOST_2=${WHEP_HOST_2:-area-2.quantumatic.live}
      - DOMAIN=${DOMAIN:-your-proxy-domain.com}
    volumes:
      - recordings:/var/recordings
      - logs:/var/log/nginx
      - certbot-etc:/etc/letsencrypt:ro
      - certbot-var:/var/lib/letsencrypt:ro
      - web-root:/var/www/html
    restart: unless-stopped
    networks:
      - rtmp-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  recordings:
  logs:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  rtmp-network:
    driver: bridge