version: '3.8'

services:
  nginx-rtmp:
    build: .
    container_name: nginx-rtmp-proxy
    ports:
      - "1935:1935"  # RTMP port
      - "80:80"       # HTTP port
      - "443:443"     # HTTPS port
    environment:
      - ORYX_SERVER_1=${ORYX_SERVER_1:-your-target-server-1.com:1935}
      - ORYX_SERVER_2=${ORYX_SERVER_2:-your-target-server-2.com:1935}
      - WHEP_SERVER_1=${WHEP_SERVER_1:-area.quantumatic.live:443}
      - WHEP_HOST_1=${WHEP_HOST_1:-area.quantumatic.live}
      - WHEP_SERVER_2=${WHEP_SERVER_2:-area-2.quantumatic.live:443}
      - WHEP_HOST_2=${WHEP_HOST_2:-area-2.quantumatic.live}
      - DOMAIN=${DOMAIN:-your-proxy-domain.com}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - recordings:/var/recordings
      - logs:/var/log/nginx
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    restart: unless-stopped
    networks:
      - rtmp-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    entrypoint: "/bin/sh"
    command: >
      -c "
      echo 'Waiting for nginx to start...';
      sleep 15;
      if [ ! -f /etc/letsencrypt/live/$${DOMAIN}/fullchain.pem ]; then
        echo 'Generating SSL certificate for domain: '$${DOMAIN};
        certbot certonly
          --webroot
          --webroot-path=/var/www/html
          --email $${EMAIL}
          --agree-tos
          --no-eff-email
          --non-interactive
          -d $${DOMAIN};
        echo 'SSL certificate generated successfully';
      else
        echo 'SSL certificate already exists for '$${DOMAIN};
      fi;
      echo 'Starting renewal daemon...';
      while :; do
        echo 'Checking for certificate renewal...';
        certbot renew --quiet --webroot --webroot-path=/var/www/html;
        echo 'Next renewal check in 12 hours...';
        sleep 43200;
      done"
    environment:
      - DOMAIN=${DOMAIN:-your-proxy-domain.com}
      - EMAIL=${EMAIL:-your-email@example.com}
    networks:
      - rtmp-network
    restart: unless-stopped

  # Optional: If you want to include your target RTMP server
  # Uncomment and configure as needed
  # oryx-server:
  #   image: your-rtmp-server-image
  #   container_name: oryx-rtmp-server
  #   ports:
  #     - "1936:1935"
  #   networks:
  #     - rtmp-network

volumes:
  recordings:
  logs:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  rtmp-network:
    driver: bridge